//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DMSpec.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DMSPEC_FORM                 101
#define IDD_REEVAL_EVALUATIONLOG        106
#define IDR_MAINFRAME                   128
#define IDR_DMSPECTYPE                  129
#define IDD_POST_FLUX_DIALOG            131
#define IDD_FLUXDIALOG                  131
#define IDB_GREEN                       133
#define IDB_YELLOW                      134
#define IDD_ROUTEDLG                    135
#define IDB_RED                         135
#define IDD_INFORMATIONDIALOG           140
#define IDD_QUERY_SELECTION_DIALOG      148
#define IDD_REALTIME_ROUTE_DLG          150
#define ID_VIEW_REALTIMEROUTE           151
#define ID_CONTROL_ADDCOMMENT           152
#define IDD_COMMENT_DLG                 153
#define IDD_REEVAL_DARK                 154
#define ID_CONTROL_REEVALUATE           155
#define IDD_REEVAL_SKY                  155
#define IDD_SOURCE_SELECTION_DLG        157
#define IDD_REEVAL_EVALUATE             158
#define IDR_FLUX_MENU                   158
#define ID_VIEW_SHOWINTENSITY           159
#define IDD_VIEW_FIT_DLG                159
#define ID_FILE                         160
#define ID_HELP161                      161
#define ID_FILE_OPENLOGFILE             162
#define ID_HELP_ABOUTMOBILEDOAS         163
#define ID_VIEW_SHOWROUTEMAP            164
#define ID_EDIT_DELETESELECTED          165
#define ID_EDIT_DELETELOWINTENSITYPOINTS 166
#define IDR_FLUX_PATH_MENU              167
#define ID__RELOAD                      168
#define ID_RELOAD_LOGFILE               169
#define ID_VIEW_COLUMNGRAPH             170
#define ID_COLUMNGRAPH_INCREASELINEWIDTH 171
#define ID_COLUMNGRAPH_DECREASELINEWIDTH 172
#define ID_FILE_RELOADTHISLOGFILE       173
#define ID_FILE_REEVALUATETHISLOGFILE   175
#define ID_FILE_CLOSEALLLOGFILES        177
#define ID_CONFIGURATION_CHANGEEXPOSURETIME 178
#define ID_VIEW_SPECTRUMFIT             179
#define IDD_FLUX_WINDFIELD_DLG          180
#define IDD_REEVAL_FITWINDOW            181
#define IDR_REEVAL_CONTEXTMENU          182
#define ID__INSERT                      183
#define ID__REMOVE                      184
#define IDR_ROUTEDLG_MENU               185
#define ID_VIEW_CHANGEBACKGROUNDCOLOR   186
#define ID_VIEW_COLORS                  187
#define ID_COLORS_BACKGROUND            188
#define ID_CHANGECOLORS_GRID            189
#define IDD_REFERENCE_PROPERTIES_DLG    189
#define ID_VIEW_GRID                    190
#define ID_GRID_INCREASE                191
#define ID_GRID_DECREASE                192
#define ID_ANALYSIS_WINDSPEEDMEASUREMENT 193
#define ID_ANALYSIS_PLUMEHEIGHTMEASUREMENT 194
#define ID__REMOVEWINDOW                194
#define IDD_POST_WINDDLG                195
#define IDD_POST_PLUMEHEIGHTDLG         196
#define ID_CONTROL_TESTTHEGPS           196
#define IDD_CONFIGURE_EVALUATION        197
#define IDD_CONFIGURE_SPECTROMETER      198
#define IDD_CONFIGURE_GPS               199
#define ID_FILE_SAVECOLUMNGRAPH         201
#define ID_FILE202                      202
#define ID_FILE_SAVEGRAPHASIMAGE        203
#define ID_CHANGECOLORS_WINDFIELD       204
#define ID_SHOWHIDESCALE                205
#define IDB_BLUE                        208
#define IDD_EXPORT_EVLOG_DIALOG         209
#define ID_FILE_EXPORTTHISLOGFILE       210
#define ID_VIEW_SHOWCOLUMNERROR         211
#define IDR_FLUX_VIEW_MENU              212
#define ID_PLOTSETTING_SETPLOTCOLOR     213
#define ID_CONTROL_STARTWINDMEASUREMENT 214
#define IDD_QUERY_STRING_DIALOG         215
#define IDR_FITWINDOWLIST_MENU          216
#define ID__INSERTFITWINDOW             217
#define ID__REMOVE218                   218
#define ID__RENAMEWINDOW                219
#define ID_VIEW_COLUMNERROR             220
#define ID_CONTROL_VIEWSPECTRAFROMSPECTROMETER 221
#define ID_VIEW_INDICATECOLUMNVALUEBY   222
#define ID_INDICATECOLUMNVALUEBY_COLOR  223
#define ID_INDICATECOLUMNVALUEBY_SIZEOFCIRCLE 224
#define ID_CHANGECOLORS_CIRCLES         225
#define ID_CHANGECOLORS_COLORSCALEBW    226
#define ID_CHANGECOLORS_COLORSCALEDEFAULT 227
#define IDB_BITMAP1                     233
#define IDB_CHALMERS                    233
#define IDR_MENU1                       235
#define IDR_REEVAL_DLG_MENU             235
#define ID_FILE_LOADSETTINGSFROMFILE    236
#define ID_FILE_SAVESETTINGSTOFILE      237
#define ID_FILE_BROWSEFOREVALUATIONLOG  238
#define ID_FILE_CLOSE239                239
#define ID_SCRIPT_CREATESCRIPT          240
#define ID_SCRIPT_RUNSCRIPT             241
#define IDD_REEVAL_SCRIPT_DLG           242
#define IDR_MENU_REEVAL_SCRIPT          243
#define ID_FILE_LOADSCRIPT              244
#define ID_FILE_SAVESCRIPT              245
#define IDD_REFERENCE_PLOT_DLG          247
#define ID_FILE_CREATEADDITIONALLOGFILE 248
#define ID_VIEW_SHOWVSTIME              249
#define ID__SHOWVSTIME                  250
#define ID_XAXISFORMAT_SHOWVSTIME       251
#define ID_VIEW_SHOWVSDISTANCETRAVELLED 252
#define ID_VIEW_SHOWVSMEASUREMENTNUMBER 253
#define ID_FILE_EXPORT_TRAVERSE_TO_KML  257
#define ID_CONTROL_CALIBRATESPECTROMETER 258
#define IDD_SPECTRUM_SETTINGS_DLG       259
#define IDD_SPECTRUM_SCALE_DLG          260
#define IDD_CONFIGURE_EVALUATION2       260
#define IDD_INSPECT_SPECTRA_DLG         261
#define ID_ANALYSIS_VIEWMEASUREDSPECTRA 262
#define ID_CONTROL_CALIBRATESPECTROMETER263 263
#define IDD_SPECTRUM_CALIBRATION        264
#define IDB_ROUTE_LEGEND                276
#define IDD_CONFIGURE_DIRECTORY         278
#define IDD_CALIBRATE_LINESHAPE_DIALOG  282
#define IDD_CALIBRATE_WAVELENGTH_DIALOG 284
#define IDD_CALIBRATE_REFERENCES        286
#define IDC_EDIT1                       1000
#define IDC_WINDSPEED                   1000
#define IDC_DLG2WS                      1000
#define IDC_FLUXDWS                     1000
#define IDC_FIXEXPTIME                  1000
#define IDC_SRC_LAT_EDIT                1000
#define IDC_COMMENT_EDIT                1000
#define IDC_EDIT_EVLOG                  1000
#define IDC_EDIT_SO2                    1000
#define IDC_PATH_WINDFIELDFILE          1000
#define IDC_REEVAL_WINDOW_FITFROM       1000
#define IDC_EDIT_EVALLOG                1000
#define IDC_EDIT_REFERENCEFILE          1000
#define IDC_EDIT_SPECCENTER             1000
#define IDC_EDIT_EXPORTFILE             1000
#define IDC_STRING_EDIT                 1000
#define IDC_EDIT_SETTINGSFILE           1000
#define IDC_EDIT_DIRECTORY              1000
#define IDC_EDIT2                       1001
#define IDC_WINDDIRECTION               1001
#define IDC_FLUXDWD                     1001
#define IDC_TIMERES                     1001
#define IDC_SRC_LON_EDIT                1001
#define IDC_NMERGE_EDIT                 1001
#define IDC_EDIT_NO2                    1001
#define IDC_REEVAL_WINDOW_FITTO         1001
#define IDC_EDIT_TIMESHIFT              1001
#define IDC_EDIT_LPITERATIONS           1001
#define IDC_EDIT_FITFROM                1001
#define IDC_EDIT_PERCENT                1001
#define IDC_EDIT_SPECSCALE_MIN          1001
#define IDC_EDIT_SLEEP                  1001
#define IDC_EDIT_O3                     1002
#define IDC_REEVAL_WINDOW_POLYNOM       1002
#define IDC_EDIT_MAXSHIFTTIME           1002
#define IDC_EDIT_FITTO                  1002
#define IDC_EDIT_SPECSCALE_MAX          1002
#define IDC_EDIT_SLEEP2                 1002
#define IDC_EDIT_DYNAMIC_RANGE          1002
#define IDC_SETBUTTON                   1003
#define IDC_EDIT_RING                   1003
#define IDC_EDIT_EVALLOG_SERIES2        1003
#define IDC_BASEEDIT                    1004
#define IDC_EDIT_SKY                    1004
#define IDC_EDIT_TESTLENGTH             1004
#define IDC_REEVAL_WINDOW_POLYNOM2      1004
#define IDC_EDIT_SKY_FILE               1004
#define IDC_EDIT_PLUMEHEIGHT            1005
#define IDC_CONCENTRATION               1006
#define IDC_EDIT_WINDDIRECTION          1006
#define IDC_SH                          1007
#define IDC_EDIT_DARKCUR_FILE           1007
#define IDC_SQ                          1008
#define IDC_EDIT_OFFSET_FILE            1008
#define IDC_LAT                         1009
#define IDC_EDIT_DARK_FILE              1009
#define IDC_LON                         1010
#define IDC_INTTIME                     1011
#define IDC_GPSTIME                     1012
#define IDC_SH2                         1013
#define IDC_TEMPERATURE                 1013
#define IDC_SCANNO                      1020
#define IDC_SPECNO                      1021
#define IDC_FLUXDLAT                    1022
#define IDC_FLUXDLON                    1023
#define IDC_FLUXDOFFSET                 1024
#define IDC_CALC                        1025
#define IDC_BTNCHOOSEFILE               1026
#define IDC_FILEPATH                    1027
#define IDC_FLUX                        1028
#define IDC_BTNFOR                      1029
#define IDC_BTNBACK                     1030
#define IDC_MAXWD                       1031
#define IDC_MAXCOL                      1032
#define IDC_SELECTION_COMBO             1032
#define IDC_AVWD                        1033
#define IDC_AVCOL                       1034
#define IDC_MAXLAT                      1035
#define IDC_MAXLON                      1036
#define IDC_AVLAT                       1037
#define IDC_AVLON                       1038
#define IDC_MAXINDEX                    1039
#define IDC_AVINDEX                     1040
#define IDC_BTNSTART                    1041
#define IDC_FLUXDFROM                   1042
#define IDC_FLUXDTO                     1043
#define IDC_PATHEDT                     1044
#define IDC_PATH_LIST                   1044
#define IDC_SETRANGEBTN                 1045
#define IDC_SLIDER1                     1049
#define IDC_SLIDERFROM                  1049
#define IDC_SIGNALLIMIT_SLIDER          1049
#define IDC_SLIDERTO                    1050
#define IDC_BTNDEL                      1053
#define IDC_SLIDEROFFSET                1054
#define IDC_SLIDERINTENSITY             1055
#define IDC_SLIDERINTENSITY_LOW         1055
#define IDC_BTNROUTE                    1056
#define IDC_SLIDERINTENSITY_HIGH        1056
#define IDC_SPECCOM                     1057
#define IDC_BTN_IMPORT_WINDFIELD        1057
#define IDC_SPECBAUD                    1058
#define IDC_USEGPSCHECK                 1059
#define IDC_FIXSHIFT                    1060
#define IDC_FIXSQUEEZE                  1061
#define IDC_BUTTON1                     1062
#define IDC_CONFCHOOSEREF               1062
#define IDC_BUTTON_BROWSE_EVLOG         1062
#define IDC_CHECK_OFFSETS               1062
#define IDC_BROWSE_SO2                  1062
#define IDC_BTN_SOURCE_LAT              1062
#define IDC_DOEVALUATION                1062
#define IDC_BTN_BROWSE_WINDFIELDFILE    1062
#define IDC_BUTTON_BROWSE_SKY           1062
#define IDC_INSERT_REFERENCE            1062
#define IDC_BTN_BROWSE_EVALLOG          1062
#define IDC_BUTTON_BROWSE_REFERENCEFILE 1062
#define IDC_BROWSE_BUTTON               1062
#define IDC_BROWSE_SETTINGSFILE         1062
#define IDC_BUTTON_SAVESPEC             1062
#define IDC_BROWSE_EVALLOG              1062
#define IDC_BROWSE_DIRECTORY            1062
#define IDC_SPECCHANNELS                1063
#define IDC_BROWSE_O3                   1063
#define IDC_BTN_SOURCE_LONG             1063
#define IDC_REMOVE_REFERENCE            1063
#define IDC_BUTTON_BROWSE_DARK          1063
#define IDC_BTN_SOURCE_LON              1063
#define IDC_BUTTON_BROWSE_REFERENCE     1063
#define IDC_BTN_BROWSE_EVALLOG_SERIES2  1063
#define IDC_BROWSE_DIR_SKY              1063
#define IDC_GPSCOM                      1064
#define IDC_BROWSE_NO2                  1064
#define IDC_REFERENCE_PROPERTIES        1064
#define IDC_BROWSE_DIR_DARK             1064
#define IDC_GPSBAUD                     1065
#define IDC_BROWSE_RING                 1065
#define IDC_REFERENCE_VIEW              1065
#define IDC_BROWSE_DIR_DARKCUR          1065
#define IDC_SPECCENTER                  1066
#define IDC_BROWSE_SKY                  1066
#define IDC_BROWSE_DIR_OFFSET           1066
#define IDC_PERCENT                     1067
#define IDC_REFFILE                     1068
#define IDC_FITFROM                     1069
#define IDC_FITTO                       1070
#define IDC_POLYNOM                     1071
#define IDC_GASFACTOR                   1072
#define IDC_MAXCOLUMN                   1073
#define IDC_EDIT_SHIFT_FIX              1073
#define IDC_NGPSSAT                     1074
#define IDC_EDIT_SQUEEZE_FIX            1074
#define IDC_EDIT_SHIFT_LINK             1075
#define IDC_EDIT_SQUEEZE_LINK           1076
#define IDC_INFORMATION                 1077
#define IDC_INTENSITY_CHECK             1081
#define IDC_COMBO2                      1087
#define IDC_ALTITUDE_COMBO              1087
#define IDC_COMBO_NCHANNELS             1087
#define IDC_HOUR_COMBO2                 1088
#define IDC_COMBO1                      1100
#define IDC_CHANNEL_COMBO               1100
#define IDC_SHIFT_COMBO_SO2             1100
#define IDC_UNIT_COMBO                  1100
#define IDC_COMBO_PORT                  1100
#define IDC_COMBO_GPS_PORT              1100
#define IDC_SHIFT_COMBO_O3              1101
#define IDC_COMBO_BAUDRATE              1101
#define IDC_COMBO_GPS_BAUDRATE          1101
#define IDC_SHIFT_COMBO_NO2             1102
#define IDC_TREE1                       1103
#define IDC_SHIFT_COMBO_RING            1104
#define IDC_BTN_DEL_LOW_INTENSITY       1106
#define IDC_BTN_DEL_INTENSITY           1106
#define IDC_FLUX_EDIT                   1107
#define IDC_FLUX_UNIT                   1108
#define IDC_BTN_DEL_HIGH_INTENSITY      1108
#define IDC_INTENSITY_EDIT              1109
#define IDC_INTENSITY_EDIT_LOW          1109
#define IDC_STATISTICS                  1110
#define IDC_ADDITIONAL_CHECK            1111
#define IDC_INTENSITY_EDIT_HIGH         1111
#define IDC_STATIC_LATITUDE             1113
#define IDC_CHECK_SHOW_SOURCE           1114
#define IDC_STATIC_LONGITUDE            1115
#define IDC_CHECK_CALC_DISTANCE         1117
#define IDC_BEARING_LABEL               1118
#define IDC_EDIT_SPECIE                 1118
#define IDC_DISTANCE_LABEL              1119
#define IDC_EDIT_PATH                   1119
#define IDC_SHOW_COLUMN                 1123
#define IDC_SHOW_ALTITUDE               1124
#define IDC_GRAPH_EXTENT                1124
#define IDC_GRAPH_BOUNDARY              1124
#define IDC_SHOW_INTENSITY              1125
#define IDC_GPS_LABEL                   1125
#define IDC_SINGLE_DARKSPECTRUM         1133
#define IDC_SEVERAL_DARKSPECTRA         1134
#define IDC_INTERPOLATE_DARK            1136
#define IDC_BOUNDARY                    1137
#define IDC_PROGRESS1                   1138
#define IDC_SINGLE_SKY                  1139
#define IDC_ALL_SKY                     1140
#define IDC_USER_SKY                    1142
#define IDC_CHECK_USESO2                1148
#define IDC_CHECK_USEO3                 1149
#define IDC_CHECK_USENO2                1150
#define IDC_CHECK_USERING               1151
#define IDC_EDIT_FITLOW                 1152
#define IDC_EDIT_FITHIGH                1153
#define IDC_EDIT_POLYNOM                1154
#define IDC_CHECK_INCLUDE_PRECALIBRATED_SKY 1155
#define IDC_GRID_BORDER                 1157
#define IDC_EVALLOG_LIST                1159
#define IDC_STATUSBAR                   1160
#define IDC_CANCEL                      1161
#define IDC_OUTPUT_LIST                 1162
#define IDC_FIT_WINDOW                  1164
#define IDC_RADIO_FIT                   1165
#define IDC_RADIO_RESIDUAL              1166
#define IDC_EDIT_IGNORE_INTENSITY       1167
#define IDC_EDIT_IGNORE_CHANNEL         1168
#define IDC_EDIT_IGNORE_SPECTRA         1169
#define IDC_RADIO_IGNORE_DARK           1170
#define IDC_RADIO_IGNORE_LIMIT          1171
#define IDC_STATIC_AVERAGE              1171
#define IDC_RADIO_IGNORE_LIST           1172
#define IDC_STATIC_EXPTIME              1172
#define IDC_STATIC_FITREGION            1173
#define IDC_EDIT_IGNORE_INTENSITY_UPPER 1173
#define IDC_STATIC_GASFACTOR            1174
#define IDC_EDIT_IGNORE_CHANNEL_UPPER   1174
#define IDC_STATIC_REFFILE              1175
#define IDC_STATIC_VERSION              1176
#define IDC_INFORMATION_AVERAGED_SPECTRA 1179
#define IDC_INFORMATION_EXPOSURE_TIME   1180
#define IDC_CHECK_LOWPASS_FILTER        1181
#define IDC_RADIO_UV                    1182
#define IDC_RADIO2                      1183
#define IDC_RADIO_VISIBLE               1183
#define IDC_RADIO_EXPTIME_AUTOMATIC     1183
#define IDC_RADIO_CHANNEL0              1183
#define IDC_WIND_GRAPH_FRAME            1184
#define IDC_RADIO_EXPTIME_FIXED         1184
#define IDC_RADIO_CHANNEL1              1184
#define IDC_CHECK_SHOW_INTERPOLATED_WINDFIELD 1185
#define IDC_RADIO_EXPTIME_ADAPTIVE      1186
#define IDC_ROUTDLG_POINTSIZEEDIT       1187
#define IDC_ROUTEDLG_POINTSIZESPIN      1188
#define IDC_CHECK_IGNORE_SELECTION_UPPER 1192
#define IDC_REEVAL_FITRESULT_DELTA      1193
#define IDC_REEVAL_FITRESULT_CHI2       1193
#define IDC_REEVAL_FITRESULT_REFERENCE1 1194
#define IDC_REEVAL_FITTYPE_DIVIDE       1194
#define IDC_REEVAL_FITRESULT_REFERENCE3 1195
#define IDC_REEVAL_FITTYPE_SUBTRACT     1195
#define IDC_REEVAL_FITRESULT_REFERENCE2 1196
#define IDC_REEVAL_FITTYPE_POLYNOMIAL   1196
#define IDC_REEVAL_FITRESULT_REFERENCE4 1197
#define IDC_REEVAL_FITWINDOWLIST        1197
#define IDC_REEVAL_PAUSE                1198
#define IDC_REEVAL_FITRESULT_SPECTRUMNO 1199
#define IDC_REEVAL_WINDOWS_GRIDFRAME    1199
#define IDC_EDIT_SKYSPEC                1200
#define IDC_REEVAL_FITRESULT_REFERENCE5 1200
#define IDC_EDIT_SKYSPEC2               1201
#define IDC_EDIT_SKYSPECDARK            1201
#define IDC_RADIO_TIME1                 1201
#define IDC_RADIO_TIME2                 1202
#define IDC_BUTTON_CALCULATE_CORRELATION 1202
#define IDC_FRAME_TIME_SERIES           1203
#define IDC_FRAME_RESULT                1204
#define IDC_RADIO_SHOW_CORR             1205
#define IDC_RADIO_SHOW_DELAY            1206
#define IDC_EDIT_ANGLESEPARATION        1206
#define IDC_RADIO_SHOW_WS               1207
#define IDC_EDIT_LATITUDE               1207
#define IDC_EDIT_LONGITUDE              1208
#define IDC_EDIT_WS_ANGLESEPARATION     1208
#define IDC_BUTTON_SOURCE_LAT           1209
#define IDC_BUTTON_SOURCE_LON           1210
#define IDC_RADIO_CONNECTION_USB        1212
#define IDC_RADIO_CONNECTION_SERIAL     1213
#define IDC_EDIT_FIXEXPTIME             1214
#define IDC_RADIO_SHIFT_FREE            1214
#define IDC_EDIT_TIMERESOLUTION         1215
#define IDC_RADIO_SHIFT_FIX             1215
#define IDC_CHECK_USEGPS                1216
#define IDC_RADIO_SQUEEZE_FREE          1216
#define IDC_EDIT_SATURATION_LOW         1216
#define IDC_CHECK1                      1217
#define IDC_CHECK_EVALUATE_FOR_SPECIE   1217
#define IDC_RADIO_SQUEEZE_FIX           1217
#define IDC_EDIT_SATURATION_HIGH        1217
#define IDC_CHECK_HIGH_PASS_FILTER      1217
#define IDC_RADIO_SHIFT_LINK            1218
#define IDC_EDIT_SATURATION_LOW2        1218
#define IDC_RADIO_CONNECTION_DIRECTORY  1218
#define IDC_CHECK_INPUT_IN_VACUUM       1218
#define IDC_RADIO_SQUEEZE_LINK          1219
#define IDC_FRAME_LANDMARKS             1220
#define IDC_LABEL_SPECIE                1220
#define IDC_COLUMNS_FRAME               1221
#define IDC_LABEL_PATH                  1221
#define IDC_STATIC_1                    1222
#define IDC_RADIO_SHIFT_FINDOPTIMAL     1222
#define IDC_RADIO_SQUEEZE_FINDOPTIMAL   1223
#define IDC_REFERENCE_FRAME             1225
#define IDC_LABEL_COLOR_SERIES1         1226
#define IDC_LABEL_COLOR_SERIES2         1227
#define IDC_LABEL_SERIES1               1228
#define IDC_LABEL_SERIES2               1229
#define IDC_EDIT_OFFSETFROM             1230
#define IDC_LABEL_COLOR_SPECTRUM        1230
#define IDC_EDIT_OFFSETTO               1231
#define IDC_LABEL_SPECTRUM              1231
#define IDC_EDIT3                       1232
#define IDC_EDIT_MAXCOLUMN              1232
#define IDC_LABEL_COLOR_SPECTRUM2       1232
#define IDC_LABEL_SPECTRUM2             1233
#define IDC_COMBO_CHANNEL               1233
#define IDC_EDIT_SETPOINT               1233
#define ID_SAVESCRIPT                   1234
#define IDC_LIST_EVALUATIONLOGS         1235
#define IDC_BUTTON_INSERTEVALLOG        1236
#define IDC_BUTTON_REMOVEEVALLOG        1237
#define IDC_BUTTON_SCANFORLOGFILES      1238
#define IDC_COMBO_MAX_N_THREADS         1239
#define IDC_PROGRESSBAR                 1240
#define IDC_LABEL_FLUXRANGE             1241
#define IDC_SPIN_EXPTIME                1242
#define IDC_SPIN_AVERAGE                1243
#define IDC_SPIN_NAVERAGE               1243
#define IDC_EDIT_NAVERAGE               1244
#define IDC_EDIT_EXPOSURETIME           1245
#define IDC_COMBO_SPECTROMETERS         1250
#define IDC_SPIN_MINVALUE               1253
#define IDC_SPIN2                       1254
#define IDC_SPIN_MAXVALUE               1254
#define IDC_SPECTRUM_GRAPH_FRAME        1254
#define IDC_LABEL_SPECTRUMNUMBER        1256
#define IDC_LABEL_EVALUATIONLOG         1257
#define IDC_SPECTRUMPROPERITES_FRAME    1259
#define IDC_SPECTRUM_SCROLLBAR          1261
#define IDC_BUTTON_VIEWSPECTRA          1266
#define IDC_FIT_GRAPH_FRAME             1267
#define IDC_BUTTON_USE_CURRENT_SPECTRUM 1269
#define IDC_PEAKLIST_FRAME              1270
#define IDC_BUTTON_FIT_POLYNOMIAL       1271
#define IDC_LABEL_POLYNOMIAL            1272
#define IDC_LABEL_POLYNOMIAL_0          1272
#define IDC_CHECK_USEAUDIO              1273
#define IDC_LABEL_MASTER                1274
#define IDC_CHECK_NODARK                1274
#define IDC_LABEL_SLAVE                 1275
#define IDC_BTN_BROWSE_EVALLOG_SERIES1  1276
#define IDC_EDIT_EVALLOG_SERIES1        1277
#define IDC_STATIC_REALTIME_PLOT        1280
#define IDC_REALTIME_ROUTE_LEGEND       1282
#define IDC_STATIC_MAXCOL               1283
#define IDC_STATIC_MINCOL               1284
#define IDC_STATIC_MIDCOL               1285
#define IDC_STATIC_SPECTRUM             1294
#define IDC_EDIT_SPECTRUM               1295
#define IDC_BUTTON_BROWSE_SPECTRUM      1296
#define IDC_STATIC_GRAPH                1297
#define IDC_BUTTON_RUN                  1297
#define IDC_BUTTON_SAVE                 1298
#define IDC_STATIC_SOLAR_ATLAS          1299
#define IDC_EDIT_SPECTRUM_DARK          1299
#define IDC_BUTTON_RUN_CREATE_REFERENCE 1299
#define IDC_EDIT_SOLAR_SPECTRUM         1300
#define IDC_BUTTON_BROWSE_SPECTRUM_DARK 1300
#define IDC_BUTTON_BROWSE_SOLAR_SPECTRUM 1301
#define IDC_STATIC_DARK_SPECTRUM        1301
#define IDC_STATIC_INITIAL_CALIBRATION  1302
#define IDC_LIST_FOUND_PEAKS            1302
#define IDC_EDIT_INITIAL_CALIBRATION    1303
#define IDC_STATIC_GRAPH_HOLDER         1303
#define IDC_RADIO_FIT_GAUSSIAN          1304
#define IDC_BUTTON_BROWSE_LINE_SHAPE    1304
#define IDC_RADIO_FIT_SUPER_GAUSSIAN    1305
#define IDC_EDIT_SPECTRUM_DARK2         1305
#define IDC_STATIC_GRAPH_HOLDER2        1305
#define IDC_RADIO_FIT_NOTHING           1306
#define IDC_BUTTON_BROWSE_SPECTRUM_DARK2 1306
#define IDC_STATIC_DARK                 1307
#define IDC_STATIC_OVERVIEWGRAPH_HOLDER 1307
#define IDC_STATIC_MINIMAP_HOLDER       1307
#define IDC_STATIC_LINEHSHAPE           1308
#define IDC_EDIT_INITIAL_CALIBRATION2   1309
#define IDC_BUTTON_BROWSE_INITIAL_CALIBRATION2 1310
#define IDC_STATIC_GRAPH_HOLDER_PANEL   1311
#define IDC_COMBO_HIGH_RES_CROSSSECTION 1312
#define IDC_STATIC_DARK2                1312
#define IDC_EDIT_CALIBRATION            1313
#define IDC_EDIT_WAVELENGTH_CALIBRATION 1314
#define IDC_LABEL_MISSING_CALIBRATION   1317
#define IDC_CALIBRATION_FROM_MERCURY_LINES 1319
#define IDC_COMBO_GRAPH_TYPE            1322
#define IDC_STATIC_CALIBRATION_FILE     1323
#define IDC_BUTTON_BROWSE_CALIBRATION_FILE 1325
#define IDC_COMBO_INITIAL_DATA_TYPE     1326
#define ID_ANALYSIS_POSTFLUX            32771
#define ID_CONTROL_STOP                 32772
#define ID_CONTROL_START                32772
#define IDD_APP_EXIT                    32773
#define ID_CONFIGURATION_PLOT           32774
#define ID_CONTROL_COUNTFLUX            32775
#define ID_VIEW_TEST                    32781
#define ID_CONFIGURATION_PLOT_CHANGEBACKGROUND 32782
#define ID_CONFIGURATION_PLOT_CHANGEPLOTCOLOR 32783
#define ID_CONFIGURATION_PLOT_CHANGEPLOTCOLOR_SLAVE 32784
#define ID_CONFIGURATION_TEST           32787
#define ID_CONFIGURATION_OPERATION      32788
#define ID_START_GPS                    32799
#define ID_CONTROL_STARTTHEGPS          32800
#define ID_CONTROL_VIEWSPECTRAFROMDIRECTORY 32801
#define ID_CONFIGURATION_               32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        289
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1327
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
